Improvements to tooling
sorokya/reoserv.net pull request #7
Opened 2024-03-30 21:04 UTC by chrzrdx

2024-03-31 11:47 UTC, sorokya requested changes
Just a couple changes requested in the markdown files. But you're a legend. I LOVE these changes. Thank you so much 😊 

I'll test these out Monday and hopefully can get merged

2024-03-31 11:47 UTC, sorokya commented on LICENSE.md
> +Copyright (c) [2024] [sorokya](https://github.com/sorokya)
Can use my name here "Richard Leek"

2024-03-31 11:47 UTC, sorokya commented on README.md
> +(authored and maintained by [sorokya][sorokya])
Can use my name here "Richard Leek"

2024-03-31 11:47 UTC, sorokya commented on README.md
> +Also, install the following VS Code extensions:
I'd denote this as optional and maybe just link to the docs for the tools rather than the vscode marketplace

2024-03-31 17:06 UTC, chrzrdx commented
> Just a couple changes requested in the markdown files. But you're a legend. I LOVE these changes. Thank you so much 😊
> 
> I'll test these out Monday and hopefully can get merged

Submitted those changes you requested for

2024-04-01 19:18 UTC, sorokya approved these changes
Some default styling issues with the new tailwind but I suspect this will be fixed with #8

2024-04-01 19:19 UTC, merged